### ISSUE TITLE
Prepare model for new order types

### ISSUE THREAD

**Issue by adamsjohanna** [assume-framework/assume#88]
For 24h bidding:
- [x] adjust make_market_config in utils.py to include count 
adjust strategies for 
- [ ] powerplants (flexable.py), 
- [ ] storages (flexable_storage.py) and  
- [x] demand and renewables (naive_strategies.py)

For learning:
- [ ] learning strategy with possible actions to choose Volume, Price and Order type

**Comment by maurerle** [comment]
@adamsjohanna I think the first step does already exist:

https://github.com/assume-framework/assume/blob/96867a97fa371810c721f3b89179eee57ce04794/assume/common/utils.py#L108-L115

So you can just set the count there, something like:

```yaml
    DAM:
      operator: DayAhead
      product_type: energy
      start_date: 2018-12-31 23:00
      products:
        - duration: 1h
          count: 24
          first_delivery: 24h
```

should be what you need
